### ISSUE TITLE
Implement Login System

### ISSUE THREAD

**Issue by WilliamDormer** [PullDating/FlutterApplication#2]
The specific mechanics need to be determined, but probably the ability for a person to enter some credentials (probably a mixture of username/pass, google auth, apple auth) in a prompt if they have an account already. This will be one of the first screens in the application. Also, this will likely include phone verification/two factor/sms verification. 

It allows us to authenticate people and determine how many are live on the app.

**Comment by PrabeshPP** [comment]
@WilliamDormer  is there any prototype design file for this page, or we can come up with UI and code that

**Comment by ethanblake4** [comment]
SMS services:
- Twilio ($0.05/sms for verify, $0.007/sms for send)
- Firebase (10k/mo free then $0.01/sms in US/Canada/India otherwise $0.06/sms) (verify only)
- Neutrino ($0.007/sms for send, number validation incl. in paid plans with other services)
