### ISSUE TITLE
app icon on home screen.

### ISSUE THREAD

**Issue by sselvanathan** [PullDating/FlutterApplication#34]
We need to implement assets like the app icon, so we can use it within the app.

**Comment by ethanblake4** [comment]
Should probably use something like https://pub.dev/packages/icons_launcher. Need to add usage instructions to readme if we do

**Comment by Ravneet6041** [comment]
I would like to walk on this, Can I get Started ?

**Comment by ethanblake4** [comment]
@Ravneet6041 sure! Can you tell me your discord username

**Comment by Ravneet6041** [comment]
Ravneet#4982

**Comment by Ravneet6041** [comment]
@ethanblake4 Can you contact me on discord? I want to ask you something

**Comment by WilliamDormer** [comment]
What's the status on this issue?
